from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path
from typing import Any, Iterable


SCHEMA_VERSION = "external-wrapper-result-v1"


def existing_path(raw: str | None) -> Path | None:
    if not raw:
        return None
    return Path(raw).expanduser()


def ensure_output_dir(path: Path) -> Path:
    path.mkdir(parents=True, exist_ok=True)
    return path


def now_run_id(input_path: Path) -> str:
    stamp = time.strftime("%Y%m%d-%H%M%S")
    stem = input_path.stem if input_path.name else "input"
    safe = "".join(ch if ch.isalnum() or ch in {"-", "_"} else "-" for ch in stem).strip("-")
    return f"{stamp}-{safe or 'input'}"


def artifact(path: Path, artifact_type: str, label: str, media_type: str | None = None) -> dict[str, Any]:
    payload: dict[str, Any] = {
        "type": artifact_type,
        "path": str(path),
        "label": label,
    }
    if media_type:
        payload["media_type"] = media_type
    return payload


def write_json(path: Path, payload: dict[str, Any] | list[Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def write_placeholder_pdf(path: Path, title: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    body = f"%PDF-1.4\n% placeholder generated by wrapper fake mode: {title}\n%%EOF\n"
    path.write_bytes(body.encode("utf-8"))


def write_placeholder_png(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(
        b"\x89PNG\r\n\x1a\n"
        b"\x00\x00\x00\rIHDR\x00\x00\x00\x01\x00\x00\x00\x01\x08\x02\x00\x00\x00\x90wS\xde"
        b"\x00\x00\x00\x0cIDATx\x9cc```\x00\x00\x00\x04\x00\x01\xf6\x178U"
        b"\x00\x00\x00\x00IEND\xaeB`\x82"
    )


def make_result(
    *,
    backend: str,
    mode: str,
    status: str,
    input_path: Path,
    output_dir: Path,
    command: list[str],
    artifacts: list[dict[str, Any]] | None = None,
    metrics: dict[str, Any] | None = None,
    warnings: list[str] | None = None,
    next_actions: list[dict[str, Any]] | None = None,
    health: dict[str, Any] | None = None,
) -> dict[str, Any]:
    return {
        "schema_version": SCHEMA_VERSION,
        "backend": backend,
        "mode": mode,
        "status": status,
        "input": str(input_path),
        "output_dir": str(output_dir),
        "command": command,
        "artifacts": artifacts or [],
        "metrics": metrics or {},
        "warnings": warnings or [],
        "next_actions": next_actions or [],
        "health": health or {},
    }


def write_result(output_dir: Path, payload: dict[str, Any]) -> Path:
    path = output_dir / "external-wrapper-result.json"
    write_json(path, payload)
    return path


def print_result(payload: dict[str, Any]) -> None:
    print(json.dumps(payload, ensure_ascii=False, indent=2))


def check_path(name: str, path: Path | None, kind: str = "file") -> dict[str, Any]:
    exists = bool(path and path.exists())
    ok_kind = exists and ((kind == "dir" and path.is_dir()) or (kind == "file" and path.is_file()) or kind == "any")
    return {
        "name": name,
        "path": str(path) if path else None,
        "exists": exists,
        "ok": bool(ok_kind),
    }


def command_available(command: str) -> bool:
    return shutil.which(command) is not None


def run_command(command: list[str], cwd: Path | None, timeout_seconds: int) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        command,
        cwd=str(cwd) if cwd else None,
        text=True,
        encoding="utf-8",
        errors="replace",
        capture_output=True,
        timeout=timeout_seconds,
        check=False,
    )


def add_common_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--input", required=True, help="Input PDF, image, or folder.")
    parser.add_argument("--output", required=True, help="Managed wrapper run directory.")
    parser.add_argument("--mode", choices=["plan", "fake", "execute"], default="plan")
    parser.add_argument("--timeout-seconds", type=int, default=120)


def parse_pages(raw: str | None) -> list[int] | str | None:
    if not raw:
        return None
    if raw.lower() == "all":
        return "all"
    pages: set[int] = set()
    for chunk in raw.split(","):
        chunk = chunk.strip()
        if not chunk:
            continue
        if "-" in chunk:
            start_raw, end_raw = chunk.split("-", 1)
            start = int(start_raw)
            end = int(end_raw)
            pages.update(range(min(start, end), max(start, end) + 1))
        else:
            pages.add(int(chunk))
    return sorted(page for page in pages if page > 0)


def page_metrics(pages: list[int] | str | None) -> dict[str, Any]:
    if pages == "all":
        return {"pages": "all"}
    if isinstance(pages, list):
        return {"page_count": len(pages), "pages": pages}
    return {}


def exit_from_status(payload: dict[str, Any]) -> int:
    return 0 if payload.get("status") in {"planned", "ok", "review", "skipped"} else 2


def main_entry(fn: Any) -> None:
    try:
        payload = fn()
    except Exception as exc:  # noqa: BLE001
        payload = {
            "schema_version": SCHEMA_VERSION,
            "status": "failed",
            "error": str(exc),
        }
    print_result(payload)
    raise SystemExit(exit_from_status(payload))

