from __future__ import annotations

from pathlib import Path


PROJECT_DIR = Path(__file__).resolve().parents[1]


def main() -> int:
    required = {
        "docs/AGENT_INTEGRATION.md": [
            "SERVICE_CONTRACT.md",
            "--baseline-results",
            "get_agent_contract",
            "ebook-agent-contract-v1",
            "benchmark-quality-comparison.json/md",
            "top-level `next_actions`",
            "copyable recommended rerun command",
            "`selection` block",
            "agent-batch-contract-v1",
            "validate_agent_batch_contract.py",
            "contract_validation",
            "Contract validation",
            "inspect_contract_validation",
            "build_agent_handoff_bundle.py",
            "build_agent_handoff_bundle",
            "handoff_status",
            "recommended_next_action",
            "artifact_summary",
            "inspect_failed_artifacts",
            "`attention`",
            "synthesizes missing",
            "inspect_agent_batch_results",
            "list_agent_batch_results",
            "--fail-on-regression",
            "test_agent_smoke_suite.py",
            "smoke summary fields",
            "agent-smoke-summary.json/md",
            "contract_validation",
            "per-test rerun commands",
            "/contract",
            "ebook-http-contract-v1",
            "--fail-fast",
            "TOC/bookmark match ratio",
            "OCR character volume",
            "structure repair decision",
            "duration",
            "enhance_job_artifact",
        ],
        "docs/TOOL_CONTRACT.md": [
            "Batch Quality Baselines",
            "get_agent_contract",
            "ebook-agent-contract-v1",
            "ebook-http-contract-v1",
            "artifact_schema_version",
            "--baseline-results",
            "`selection` block",
            "`contract` block",
            "validate_agent_batch_contract.py",
            "contract_validation",
            "Contract validation",
            "inspect_contract_validation",
            "agent-handoff-bundle.json/md",
            "build_agent_handoff_bundle",
            "agent_handoff_bundle_json",
            "handoff_status",
            "recommended_next_action",
            "artifact_summary",
            "read_run_summary",
            "`attention` triage block",
            "backward-compatible",
            "rerun_failed_or_review",
            "powershell_command",
            "inspect_agent_batch_results",
            "list_agent_batch_results",
            "completed-with-review",
            "online_providers.example.json",
            "EBOOK_CONVERTER_ONLINE_PROVIDERS_CONFIG",
            "online_provider_health",
            "without making remote API calls",
            "minimal_ok",
            "optional_missing_is_ok",
            "media_helper",
            "python_dependency_consistency",
            "local_env_loaded_keys",
            "must not contain secret values",
            "enhance_job_artifact",
            "GOT-OCR explicit image OCR wrapper",
            "scripts/got_ocr_image_to_md.py",
            "GOT_OCR_SCRIPT",
            "GOT_OCR_MODEL",
            "DeepSeek-OCR explicit VLM OCR wrapper",
            "scripts/deepseek_ocr_image_to_md.py",
            "DEEPSEEK_OCR_PYTHON",
            "DEEPSEEK_OCR_MODEL",
        ],
        "examples/agent-batch/README.md": [
            "--baseline-results",
            "benchmark-quality-comparison.json/md",
            "machine-readable `selection` block",
            "artifact_summary",
            "inspect_review_items",
            "top-level `next_actions`",
            "copyable recommended rerun command",
            "--fail-on-regression",
        ],
        "examples/agent-batch/AGENT_PROMPT_TEMPLATE.md": [
            "--baseline-results",
            "benchmark-quality-comparison.md",
            "top-level `next_actions`",
            "powershell_command",
            "inspect_agent_batch_results",
            "list_agent_batch_results",
            "Quality comparison status",
        ],
        "README.md": [
            "docs/SERVICE_CONTRACT.md",
            "docs/QUICKSTART.md",
            "docs/BACKENDS.md",
            "docs/PROJECT_OVERVIEW.md",
            "docs/ARCHITECTURE_DIAGRAM.md",
            "Referenced And Reused Tools",
            "test_agent_fast_contract.py",
            "test_agent_batch_contract_validator.py",
            "test_agent_handoff_bundle.py",
            "test_agent_smoke_suite.py",
            "summary 报告结构",
            "agent-smoke-summary.json/md",
            "contract_validation",
            "逐条重跑命令",
            "--fail-fast",
            "test_agent_contract.py",
            "inspect_agent_batch_results",
            "list_agent_batch_results",
            "build_agent_handoff_bundle",
            "get_agent_contract",
            "cli_agent_batch_handoff.py",
            "http_agent_batch_handoff.py",
            "完整 agent contract",
            "目录/书签匹配率",
            "OCR 字符量",
            "运行时间",
            "benchmark-quality-comparison.json/md",
            "check_project_readiness.py",
            "check_public_release.py",
            "generate_backend_scorecard.py",
            "prepare_github_release_notes.py",
            "optional backend scorecard",
            "project-readiness.json/md",
            "test_minimal_entrypoints.py",
            "公开 TXT fixture",
        ],
        "docs/RELEASE_CHECKLIST.md": [
            "python scripts\\run_quality_gate.py --profile release",
            "python scripts\\check_public_release.py",
            "python scripts\\show_latest_quality_gate.py",
            "python scripts\\prepare_github_release_notes.py --version vX.Y.Z --output .\\release-notes.md",
            "redacts local absolute paths",
            "--include-local-paths",
        ],
        "docs/SERVICE_CONTRACT.md": [
            "on-demand",
            "`8765` is not the current contract port",
            "config/http.env",
            "EBOOK_CONVERTER_HTTP_PORT=9241",
            "MCP stdio",
            "HTTP bridge",
            "CLI",
            "needs_manual_start",
            "OpenClaw",
            "host.docker.internal",
        ],
        "docs/GITHUB_RELEASE_TEMPLATE.md": [
            "python scripts\\prepare_github_release_notes.py --version vX.Y.Z --output .\\release-notes.md",
            "python scripts\\run_quality_gate.py --profile release",
            "python scripts\\show_latest_quality_gate.py",
            "Third-Party Notices",
        ],
        "docs/QUICKSTART.md": [
            "git clone",
            "python -m pip install -r requirements.txt",
            "python book_converter_ui.py",
            "python batch_convert_books.py",
            "python scripts\\run_quality_gate.py --profile minimal",
            "RELEASE_CHECKLIST.md",
        ],
        "docs/BACKENDS.md": [
            "Pandoc",
            "Calibre",
            "PyMuPDF4LLM",
            "Docling",
            "Apache Tika",
            "GROBID",
            "MinerU",
            "Marker",
            "MarkItDown",
            "OCRmyPDF",
            "pdf-craft",
            "pdfplumber",
            "Camelot",
            "Tabula",
            "RapidOCR",
            "CnOCR",
            "Umi-OCR",
            "Pix2Text",
            "Surya",
            "GOT-OCR",
            "DeepSeek-OCR",
            "commercial-use terms",
            "olmOCR",
            "not main Markdown conversion",
            "backend-scorecard.json/md",
        ],
        "docs/PROJECT_OVERVIEW.md": [
            "GitHub About Text",
            "Architecture",
            "ARCHITECTURE_DIAGRAM.md",
            "Referenced And Reused Open-Source Tools",
            "Direct integration",
            "Architecture reference",
            "Pandoc",
            "Calibre",
            "PyMuPDF4LLM",
            "MinerU",
            "Marker",
            "Docling",
            "Apache Tika",
            "GROBID",
            "pdf-craft",
            "olmOCR",
            "Tabula",
            "Umi-OCR",
            "CnOCR",
            "Pix2Text",
            "Surya",
            "GOT-OCR",
            "DeepSeek-OCR",
            "Agent-Facing Contract",
            "does not vendor",
        ],
        "docs/ARCHITECTURE_DIAGRAM.md": [
            "One-Page Map",
            "Entry points",
            "Preflight inspection",
            "Routing and recovery",
            "Pandoc",
            "Calibre",
            "PyMuPDF4LLM",
            "MinerU",
            "Marker",
            "Docling",
            "Apache Tika",
            "GROBID",
            "pdf-craft",
            "olmOCR",
            "Tabula",
            "Umi-OCR",
            "CnOCR",
            "Pix2Text",
            "Surya",
            "GOT-OCR",
            "DeepSeek-OCR",
            "PaddleOCR-VL",
            "Reference Patterns",
            "does not vendor",
        ],
        "docs/ARCHITECTURE.md": [
            "System Overview",
            "Online Provider Boundary",
            "config/online_providers.example.json",
            "PDF And Image Routing",
            "Third-Party Boundary",
            "Pandoc",
            "Calibre",
            "PyMuPDF4LLM",
            "MinerU",
            "Marker",
            "Docling",
            "Apache Tika",
            "GROBID",
            "pdf-craft",
            "olmOCR",
            "Tabula",
            "Umi-OCR",
            "CnOCR",
            "Pix2Text",
            "Surya",
            "GOT-OCR",
            "DeepSeek-OCR",
        ],
        "docs/REFERENCES_AND_REUSE.md": [
            "Direct Tool Integration",
            "Architecture Patterns Referenced",
            "Pandoc",
            "Calibre",
            "PyMuPDF4LLM",
            "MinerU",
            "Marker",
            "Docling",
            "Apache Tika",
            "GROBID",
            "pdf-craft",
            "olmOCR",
            "Tabula",
            "Umi-OCR",
            "CnOCR",
            "Pix2Text",
            "Surya",
            "GOT-OCR",
            "DeepSeek-OCR",
            "does not vendor",
        ],
        "docs/ONLINE_MODEL_API_INTEGRATION.md": [
            "online_providers.example.json",
            "online_models.example.json",
            "remote_ocr_vlm_eval.example.json",
            "run_remote_ocr_vlm_eval.py",
            "OpenAI-compatible adapter",
            "OcrLayoutProvider",
            "VlmLayoutProvider",
            "TextStructureProvider",
            "EmbeddingProvider",
        ],
        "docs/OPTIONAL_OCR_VLM_REPLACEMENT_RESEARCH.md": [
            "PaddleOCR-VL",
            "Surya",
            "Pix2Text",
            "MinerU VLM",
            "olmOCR",
            "Qwen-VL",
            "DeepSeek-OCR",
            "GOT-OCR",
            "run_remote_ocr_vlm_eval.py",
            "--execute --allow-remote",
            "--execute --fake",
        ],
        "docs/INSTALLATION.md": [
            "online_providers.example.json",
            "EBOOK_CONVERTER_ONLINE_PROVIDERS_CONFIG",
            "requirements-pdfcraft.txt",
            "requirements-surya.txt",
            "requirements-tabula.txt",
            "requirements-cnocr.txt",
            "requirements-olmocr.txt",
            "requirements-got-ocr.txt",
            "requirements-deepseek-ocr.txt",
            "EBOOK_CONVERTER_TIKA_SERVER_URL",
            "EBOOK_CONVERTER_GROBID_SERVER_URL",
            "GOT_OCR_SCRIPT",
            "GOT_OCR_MODEL",
            "DEEPSEEK_OCR_PYTHON",
            "DEEPSEEK_OCR_MODEL",
            "pdfcraft",
            "online_models.example.json",
            "OCR_LAYOUT_API_KEY",
            "TABLE_LLM_API_KEY",
            "EMBEDDING_API_KEY",
        ],
        "examples/agent-calls/README.md": [
            "Agent Batch Handoff",
            "cli_agent_batch_handoff.py list",
            "cli_agent_batch_handoff.py inspect",
            "http_agent_batch_handoff.py",
        ],
        "examples/agent-recipes/README.md": [
            "structure-enhancement.md",
            "online-enhancement.md",
            "enhance_markdown_structure",
            "enhance_job_artifact",
            "Weak heading hierarchy",
        ],
        "examples/agent-recipes/online-enhancement.md": [
            "run_online_enhancement",
            "run_online_enhancement.py",
            "provider_mode",
            "openai_compatible",
            "model_mode",
            "hybrid",
            "allow_remote",
            "online-enhancement-<task>.json/md",
        ],
        "examples/agent-recipes/structure-enhancement.md": [
            "enhance_markdown_structure",
            "enhance_job_artifact",
            "enhance_markdown_structure.py",
            "model_mode",
            "local",
            "overwrite",
            "false",
            ".structure-enhanced",
            "allow_remote=true",
            "local_structure_repair.decisions",
            "review_report",
        ],
    }
    for relative, needles in required.items():
        text = (PROJECT_DIR / relative).read_text(encoding="utf-8")
        missing = [needle for needle in needles if needle not in text]
        if missing:
            raise AssertionError(f"{relative} missing required contract text: {missing}")
    print("Docs contract smoke test passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
