from __future__ import annotations

from pathlib import Path


PROJECT_DIR = Path(__file__).resolve().parents[1]


def main() -> int:
    required = {
        "docs/AGENT_INTEGRATION.md": [
            "--baseline-results",
            "get_agent_contract",
            "ebook-agent-contract-v1",
            "benchmark-quality-comparison.json/md",
            "top-level `next_actions`",
            "copyable recommended rerun command",
            "`selection` block",
            "agent-batch-contract-v1",
            "validate_agent_batch_contract.py",
            "contract_validation",
            "Contract validation",
            "inspect_contract_validation",
            "build_agent_handoff_bundle.py",
            "build_agent_handoff_bundle",
            "handoff_status",
            "recommended_next_action",
            "artifact_summary",
            "inspect_failed_artifacts",
            "`attention`",
            "synthesizes missing",
            "inspect_agent_batch_results",
            "list_agent_batch_results",
            "--fail-on-regression",
            "test_agent_smoke_suite.py",
            "smoke summary fields",
            "agent-smoke-summary.json/md",
            "contract_validation",
            "per-test rerun commands",
            "/contract",
            "ebook-http-contract-v1",
            "--fail-fast",
        ],
        "docs/TOOL_CONTRACT.md": [
            "Batch Quality Baselines",
            "get_agent_contract",
            "ebook-agent-contract-v1",
            "ebook-http-contract-v1",
            "artifact_schema_version",
            "--baseline-results",
            "`selection` block",
            "`contract` block",
            "validate_agent_batch_contract.py",
            "contract_validation",
            "Contract validation",
            "inspect_contract_validation",
            "agent-handoff-bundle.json/md",
            "build_agent_handoff_bundle",
            "agent_handoff_bundle_json",
            "handoff_status",
            "recommended_next_action",
            "artifact_summary",
            "read_run_summary",
            "`attention` triage block",
            "backward-compatible",
            "rerun_failed_or_review",
            "powershell_command",
            "inspect_agent_batch_results",
            "list_agent_batch_results",
            "completed-with-review",
            "online_providers.example.json",
            "EBOOK_CONVERTER_ONLINE_PROVIDERS_CONFIG",
            "online_provider_health",
            "without making remote API calls",
        ],
        "examples/agent-batch/README.md": [
            "--baseline-results",
            "benchmark-quality-comparison.json/md",
            "machine-readable `selection` block",
            "artifact_summary",
            "inspect_review_items",
            "top-level `next_actions`",
            "copyable recommended rerun command",
            "--fail-on-regression",
        ],
        "examples/agent-batch/AGENT_PROMPT_TEMPLATE.md": [
            "--baseline-results",
            "benchmark-quality-comparison.md",
            "top-level `next_actions`",
            "powershell_command",
            "inspect_agent_batch_results",
            "list_agent_batch_results",
            "Quality comparison status",
        ],
        "README.md": [
            "docs/PROJECT_OVERVIEW.md",
            "Referenced And Reused Tools",
            "test_agent_fast_contract.py",
            "test_agent_batch_contract_validator.py",
            "test_agent_handoff_bundle.py",
            "test_agent_smoke_suite.py",
            "summary 报告结构",
            "agent-smoke-summary.json/md",
            "contract_validation",
            "逐条重跑命令",
            "--fail-fast",
            "test_agent_contract.py",
            "inspect_agent_batch_results",
            "list_agent_batch_results",
            "build_agent_handoff_bundle",
            "get_agent_contract",
            "cli_agent_batch_handoff.py",
            "http_agent_batch_handoff.py",
            "完整 agent contract",
            "目录/书签匹配率",
            "OCR 字符量",
            "运行时间",
        ],
        "docs/PROJECT_OVERVIEW.md": [
            "GitHub About Text",
            "Architecture",
            "Referenced And Reused Open-Source Tools",
            "Pandoc",
            "Calibre",
            "PyMuPDF4LLM",
            "MinerU",
            "Marker",
            "Docling",
            "Umi-OCR",
            "Agent-Facing Contract",
            "does not vendor",
        ],
        "docs/ARCHITECTURE.md": [
            "System Overview",
            "Online Provider Boundary",
            "config/online_providers.example.json",
            "PDF And Image Routing",
            "Third-Party Boundary",
            "Pandoc",
            "Calibre",
            "PyMuPDF4LLM",
            "MinerU",
            "Marker",
            "Docling",
            "Umi-OCR",
        ],
        "docs/REFERENCES_AND_REUSE.md": [
            "Direct Tool Integration",
            "Architecture Patterns Referenced",
            "Pandoc",
            "Calibre",
            "PyMuPDF4LLM",
            "MinerU",
            "Marker",
            "Docling",
            "Umi-OCR",
            "does not vendor",
        ],
        "docs/ONLINE_MODEL_API_INTEGRATION.md": [
            "online_providers.example.json",
            "online_models.example.json",
            "OpenAI-compatible adapter",
            "OcrLayoutProvider",
            "VlmLayoutProvider",
            "TextStructureProvider",
            "EmbeddingProvider",
        ],
        "docs/INSTALLATION.md": [
            "online_providers.example.json",
            "EBOOK_CONVERTER_ONLINE_PROVIDERS_CONFIG",
            "online_models.example.json",
            "OCR_LAYOUT_API_KEY",
            "TABLE_LLM_API_KEY",
            "EMBEDDING_API_KEY",
        ],
        "examples/agent-calls/README.md": [
            "Agent Batch Handoff",
            "cli_agent_batch_handoff.py list",
            "cli_agent_batch_handoff.py inspect",
            "http_agent_batch_handoff.py",
        ],
        "examples/agent-recipes/README.md": [
            "structure-enhancement.md",
            "online-enhancement.md",
            "enhance_markdown_structure",
            "Weak heading hierarchy",
        ],
        "examples/agent-recipes/online-enhancement.md": [
            "run_online_enhancement",
            "run_online_enhancement.py",
            "provider_mode",
            "openai_compatible",
            "model_mode",
            "hybrid",
            "allow_remote",
            "online-enhancement-<task>.json/md",
        ],
        "examples/agent-recipes/structure-enhancement.md": [
            "enhance_markdown_structure",
            "enhance_markdown_structure.py",
            "model_mode",
            "local",
            "overwrite",
            "false",
            ".structure-enhanced",
            "allow_remote=true",
            "local_structure_repair.decisions",
            "review_report",
        ],
    }
    for relative, needles in required.items():
        text = (PROJECT_DIR / relative).read_text(encoding="utf-8")
        missing = [needle for needle in needles if needle not in text]
        if missing:
            raise AssertionError(f"{relative} missing required contract text: {missing}")
    print("Docs contract smoke test passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
